# Copyright 2026 JetBrains s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_ENUM_FILE_TEMPLATE = """
// generated by //private/rules:kt_aspect_enum.bzl - do not edit

package %s

import com.intellij.aspect.lib.Rules

enum class Modules(
  val file: String,
  val rulesets: List<Rules>,
) {
%s
}
"""

_ENUM_ENTRY_TEMPLATE = """
{name}(
    file = "{file}",
    rulesets = listOf({rulesets}),
),
"""

_AspectModule = provider(
    doc = "Internal provider to pass an aspect defitinion to a rule.",
    fields = ["file", "rulesets"],
)

def _aspect_module_impl(ctx):
    return [_AspectModule(file = ctx.attr.file, rulesets = ctx.attr.rulesets)]

_aspect_module = rule(
    implementation = _aspect_module_impl,
    attrs = {
        "file": attr.string(mandatory = True),
        "rulesets": attr.string_list(default = []),
    },
)

def _format_entry(module):
    return _ENUM_ENTRY_TEMPLATE.format(
        name = module.file.upper(),
        file = module.file,
        rulesets = ", ".join(['Rules.%s' % it for it in module.rulesets]),
    )

def _kt_aspect_enum_impl(ctx):
    entries = "\n".join([_format_entry(it[_AspectModule]) for it in ctx.attr.modules])
    content = _ENUM_FILE_TEMPLATE % (ctx.attr.package, entries)

    file = ctx.actions.declare_file("%s.kt" % ctx.label.name)
    ctx.actions.write(file, content)

    return [DefaultInfo(files = depset([file]))]

_kt_aspect_enum = rule(
    implementation = _kt_aspect_enum_impl,
    attrs = {
        "modules": attr.label_list(mandatory = True),
        "package": attr.string(mandatory = True),
    },
)

def kt_aspect_enum(name, modules, **kwargs):
    for module in modules:
        _aspect_module(
            name = "%s_%s" % (name, module.file),
            file = module.file,
            rulesets = module.rulesets,
        )

    _kt_aspect_enum(
        name = name,
        modules = ["%s_%s" % (name, module.file) for module in modules],
        **kwargs
    )
