load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    fixture = "//testing/fixtures/go:simple",
    test = "SimpleTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/go:simple_old",
    test = "SimpleTest.kt",
    test_name = "SimpleTestOld",
)
