header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: JetBrains s.r.o.
  paths:
    - '**/*.kt'
    - '**/*.java'
    - '**/*.bzl'
    - '**/*.proto'
    - '**/*.py'
  paths-ignore:
    - 'common/third_party/**'
    - 'testing/fixtures/**'
    - 'private/repos/common.bzl'
  comment: on-failure
  language:
    Starlark:
      extensions:
        - ".bzl"
        - ".bazel"
      comment_style_id: PythonStyle
