load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("//testing/rules:defs.bzl", "junit_test")

kt_jvm_library(
    name = "utils",
    srcs = ["utils.kt"],
    visibility = ["//testing/tests:__subpackages__"],
    deps = [
        "//sdk/proto:ide_info_java_proto",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

junit_test(
    data = ["//:archive_ide"],
    env = {
        "ARCHIVE_IDE": "$(rlocationpaths //:archive_ide)",
    },
    test = "DeployTest.kt",
    deps = [
        "//sdk/lib:deploy",
        "@rules_java//java/runfiles",
    ],
)

junit_test(
    test = "DeployFileTest.kt",
    deps = [
        "//sdk/lib:deploy",
    ],
)
