load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    fixture = "//testing/fixtures/java:simple",
    test = "SimpleTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/java:macro",
    test = "MacroTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/java:plugin",
    test = "PluginTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/java:forwardedArtifacts",
    test = "ForwardTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/java:resources",
    test = "ResourcesTest.kt",
)
