load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    fixture = "//testing/fixtures/cpp:simple",
    test = "TargetTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:simple",
    test = "BuildFileTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:transition",
    test = "TransitionTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:transition",
    test = "ExecConfigTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/general:simple",
    test = "GeneralTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/general:custom_rules",
    test = "CustomRuleTest.kt",
)
