/*
 * Copyright 2026 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.intellij.aspect.lib

import com.intellij.aspect.private.lib.utils.asBazelPath
import java.io.IOException
import java.nio.file.Files
import java.nio.file.Path
import java.util.Locale

/**
 * Creates the config directory and writes the config file as well as the
 * required BUILD file.
 */
@Throws(IOException::class)
fun writeAspectConfig(destination: Path, relativeDestination: Path, config: AspectConfig) {
  val directory = destination.resolve("config")
  Files.createDirectories(directory)

  val buildFile = directory.resolve("BUILD")
  writeFileIfContentDiffers(buildFile, generateBuildFile(relativeDestination))

  val configFile = directory.resolve("config.bzl")
  writeFileIfContentDiffers(configFile, generateConfigStruct(config))

  val aspectFile = directory.resolve("aspect.bzl")
  writeFileIfContentDiffers(aspectFile, generateAspectConfig(relativeDestination, config))
}

private fun generateBuildFile(relativeDestination: Path): String {
  val prefix = asBazelPath(relativeDestination)

  return """
# generated by //sdk/lib/config.kt - do not edit

load("//$prefix/modules:module.bzl", "intellij_module")

intellij_module.container(
    name = "module_container",
    visibility = ["//visibility:public"],
)
""".trimIndent()
}

private fun generateConfigStruct(config: AspectConfig) = """
# generated by //sdk/lib/config.kt - do not edit

config = struct(
	bazel_version = "${config.bazelVersion}",
  os = "${System.getProperty("os.name").lowercase(Locale.ROOT)}",
)
"""

private fun generateAspectConfig(relativeDestination: Path, config: AspectConfig): String {
  val modules = modulesForRules(config.rulesets ?: (config.useBuiltin + config.repoMapping.keys))
  val prefix = asBazelPath(relativeDestination)

  val files = modules.joinToString(", ") { it.file }
  val loads = modules.map { it.file }.joinToString("\n") { """load("//$prefix/modules:$it.bzl", $it = "module")""" }

  return """
# generated by //sdk/lib/config.kt - do not edit

load("//$prefix/intellij:aspect.bzl", "intellij_configure_aspect")
$loads

MODULES = [$files]

intellij_aspect = intellij_configure_aspect(
    modules = MODULES,
    container = "//$prefix/config:module_container",
)
"""
}
