/*
 * Copyright 2026 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.intellij.aspect.lib

import com.google.devtools.intellij.ideinfo.IntellijIdeInfo.TargetIdeInfo
import com.google.protobuf.TextFormat
import java.io.IOException
import java.nio.file.Path
import kotlin.io.path.reader

// Read a textproto message generated by this aspect from a file
fun readTargetFromFile(file: Path, logErrorMessage: (String?) -> Unit = {}): TargetIdeInfo? {
  val builder = TargetIdeInfo.newBuilder()
  val parser =
    TextFormat.Parser
      .newBuilder()
      .setAllowUnknownFields(true)
      .build()
  try {
    file.reader().use {
      parser.merge(it, builder)
    }
  } catch (e: IOException) {
    logErrorMessage(e.message)
    return null
  }
  return builder.build()
}
