load("@bazel_skylib//rules:common_settings.bzl", "int_flag", "string_flag")

int_flag(
    name = "max_servers",
    build_setting_default = 1,
    visibility = ["//visibility:public"],
)

string_flag(
    name = "repo_cache",
    build_setting_default = "",
    visibility = ["//visibility:public"],
)

string_flag(
    name = "worker_dir",
    build_setting_default = "",
    visibility = ["//visibility:public"],
)
